# This is a basic workflow to help you get started with Actions

name: Mirroring

on: [push, delete]

jobs:
  to_gitlab:
    runs-on: ubuntu-18.04
    steps:                                              # <-- must use actions/checkout@v1 before mirroring!
    - uses: actions/checkout@v1
    - uses: n0bra1n3r/repository-mirroring-action@v2
      with:
        target_repo_url:
          git@iis-git.ee.ethz.ch:wiesep/crazyflie-stepStabilizer.git
        ssh_private_key:                                # <-- use 'secrets' to pass credential information.
          ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}
